title: Maschinendeck

name: Maschinendeck
url: https://maschinendeck.org
description: Hacker-, Maker- & Nerdspace in Trier, Germany

permalink: /:year/:month/:day/:title/
# paginate: 10
# highlighter: pygments

baseurl: "" # the subpath of your site, e.g. /blog
email: kontakt@maschinendeck.org
twitter_username: Maschinendeck_
github_username:  maschinendeck


t:
  de:
    home:
      name: "Home"
      url: "/"
    room:
      name: "Der Raum"
      url: "/raum/"
    events:
        name: "Termine"
        url: "/events/"
    about:
      name: "Verein"
      url: "/about/"
    FAQ:
      name: "FAQ"
      url: "/faq/"
    contact:
      name: "Kontakt & Anfahrt"
      url: "/contact/"
    Wiki:
      name: "Wiki"
      url: "https://wiki.maschinendeck.org/"
  en:
    home:
      name: "Home"
      url: "/index_en/"
    room:
      name: "Space"
      url: "/raum_en/"
    events:
        name: "Events"
        url: "/events_en/"
    about:
      name: "About"
      url: "/about_en/"
    contact:
      name: "Contact"
      url: "/contact_en/"
    Wiki:
      name: "Wiki"
      url: "https://wiki.maschinendeck.org/"

port: 4010

# Build settings
markdown: kramdown
